### ISSUE TITLE
MT7603U chip does not support

### ISSUE THREAD

**Issue by qiuzhu** [chris1111/WIFI-Network-macOS-High-Sierra#1]
I have a usb wifi ，and I check the chip , it is MT7603U , I install this app , but it does not work . How can I made it work:

> product  ID：	0x760c
   vendor ID：	0x0e8d  (MediaTek Inc.)

**Comment by chris1111** [comment]
MT7603U is not support by this App

You can try this one replace Drivers on  EFI /CLOVER/kexts/10.13
[RT2870USBWirelessDriver.kext.zip](https://github.com/chris1111/WIFI-Network-macOS-High-Sierra/files/1686347/RT2870USBWirelessDriver.kext.zip)

Not sure if this work?

**Comment by qiuzhu** [comment]
thank you , and I try it  but it not work , maybe this chip is so special , and I only find the linux driver 
https://github.com/U2FsdGVkX1/MT7603U
