### ISSUE TITLE
wireless utility is not opening

### ISSUE THREAD

**Issue by savigny030** [chris1111/WIFI-Network-macOS-High-Sierra#2]
I'm on a hackintosh and be using a usb wifi dongle with 0x7601 0x148f ID it is a RT2870 chip.
After Install and restart the UI on the home screen won't open...

**Comment by savigny030** [comment]
the chip won't be detect. not even in System Preferences -> Network. 
system_profiler SPUSBDataType in terminal gives me:

```
802.11 n WLAN:

          Product ID: 0x7601
          Vendor ID: 0x148f
          Version: 0.00
          Serial Number: 1.0
          Speed: Up to 12 Mb/sec
          Manufacturer: MediaTek
          Location ID: 0x12100000 / 3
          Current Available (mA): 500
          Current Required (mA): 160
          Extra Operating Current (mA): 0
```

Maybe you could help out.
the problem is my internal pcie card: Asus PCE AC51 is not working with your usb Realtek driver.
the IDs of that device are 10ec 8812 and device is RTL8812AE wich is not supported...

**Comment by chris1111** [comment]
> the chip won't be detect. not even in System Preferences -> Network.
> system_profiler SPUSBDataType in terminal gives me:
> 
> ```
> 802.11 n WLAN:
> 
>           Product ID: 0x7601
>           Vendor ID: 0x148f
>           Version: 0.00
>           Serial Number: 1.0
>           Speed: Up to 12 Mb/sec
>           Manufacturer: MediaTek
>           Location ID: 0x12100000 / 3
>           Current Available (mA): 500
>           Current Required (mA): 160
>           Extra Operating Current (mA): 0
> ```
> Maybe you could help out.
> the problem is my internal pcie card: Asus PCE AC51 is not working with your usb Realtek driver.
> the IDs of that device are 10ec 8812 and device is RTL8812AE wich is not supported...

**Comment by savigny030** [comment]
I will try later, thank you :) sorry i was busy yesterday... Do you think its maybe possible to get that PCE AC51 working? I mean its an RTL8812 chip, the RTL8812AU is supported but my RTL8812AE isnt supported yet... Would be very nice to use my pcie wifi card instead of the usb stick thingi...
Greetings from germany!

**Comment by chris1111** [comment]
RTL8812AU take a look here
https://github.com/chris1111/Wireless-USB-Adapter-Clover

Or maybe here 
https://github.com/chris1111/WIFI-USB-Adapter

**Comment by mikejrh** [comment]
Your wifi installer worked for my PAU07 Panda USB adapter (chipset RT5372) on Mojave until the last beta update 10.14.4 Beta (18E184e). This was using your more recent Release V2. The wireless utility opens on startup and then crashes.  Any thoughts ? Thank you.

**Comment by chris1111** [comment]
> Your wifi installer worked for my PAU07 Panda USB adapter (chipset RT5372) on Mojave until the last beta update 10.14.4 Beta (18E184e). This was using your more recent Release V2. The wireless utility opens on startup and then crashes. Any thoughts ? Thank you.

Try to Uninstall , reboot and reinstall and reboot again

**Comment by mikejrh** [comment]
uninstalled, reboot, reinstalled, reboot;     same problem.

**Comment by chris1111** [comment]
I dont have Beta a 18E184e to test and view

**Comment by chris1111** [comment]
I dont have Beta 18E184e to test and view

**Comment by mikejrh** [comment]
would a copy of the wireless utility crash log report be of help ?

**Comment by chris1111** [comment]
> would a copy of the wireless utility crash log report be of help ?

not really

**Comment by chris1111** [comment]
> would a copy of the wireless utility crash log report be of help ?

Why posting a different link to Insanelymac ? Anyway this utility here is for High Sierra not Mojave

**Comment by chris1111** [comment]
> Your wifi installer worked for my PAU07 Panda USB adapter (chipset RT5372) on Mojave until the last beta update 10.14.4 Beta (18E184e). This was using your more recent Release V2. The wireless utility opens on startup and then crashes. Any thoughts ? Thank you.

Why posting a different link to Insanelymac ? Anyway this utility here is for High Sierra not Mojave
I will delete your comment here
