### ISSUE TITLE
WirelessUtility[629]: OidQueryInformation [Line 198] OidQueryInformation ==> NoDriver 

### ISSUE THREAD

**Issue by Justsoos** [chris1111/WIFI-Network-macOS-High-Sierra#4]
I tried on High Sierra 10.13.6 with RT3070, both driver from MediaTek 
https://www.mediatek.com/products/broadbandWifi/rt3070
 urs and many other ways.

but none could identify the usb wifi, always show not connect, and strangely once the command `system_profiler SPUSBDataType`
shows the correct info of this usb card which I forgot the exact environment, because I installed urs chris1111/WIFI-Network-macOS-High-Sierra and chris1111/USB-Wireless-Utility and others one by one... even I installed the kext with EasyKext Utility.app v2, none works.
but the two RT3070 cards work well in Windows 10. 

and now I tried chris1111 / WIFI-Network-macOS-High-Sierra and found lots in Consoles logs:
```
--- last message repeated 14 times ---
WirelessUtility[629]: OidQueryInformation [Line 198] OidQueryInformation ==> NoDriver 
```
every time click the Open Wireless Utility on status bar, the logs will add one, and no utility windows shown.
I tried EasyKext Utility.app v2 to install drivers individually, still not work.

and I disable SIP already.
any info would be appreciated.

BTW, seems urs install program have no UN-install part, now my Mac might be too messy ;P

**Comment by Justsoos** [comment]
BTW, you provided video:
```
https://www.youtube.com/watch?v=eCrspCSJ3_8
```
"Video unavailable"
at 
https://www.insanelymac.com/forum/topic/299948-usb-wifi-updated-ralinkmediatek-rt2870-rt2770-rt3x7x-rt537x-rt5572/?do=findComment&comment=2641181

**Comment by chris1111** [comment]
Why not Reading the Readme correctly ??????


This utility is Update here ➣ [USB-Wireless-Utility](https://github.com/chris1111/USB-Wireless-Utility) - Working for 10.6 to 10.14
